development:
  adapter: postgresql
  encoding: unicode
  database: musecruise_development
  pool: 5
  username: fred
  password: tastywave

test:
  adapter: postgresql
  encoding: unicode
  database: musecruise_test
  pool: 5
  username: fred
  password: tastywave

